[package]
name = "polars_io_tools"
version = "0.1.1"
authors = ["Point72, L.P. <OpenSource@point72.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/Point72/polars io tools"
description = "Custom parsing extensions for lazy polars"

[lib]
name = "polars_io_tools"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
arrow = { version = "58", features = ["ffi"] }
chrono = "0.4"
futures-util = "0.3"
tiberius = { git = "https://github.com/Yvictor/tiberius.git", rev = "9eca5b8798bc70a76bc1cb336b237bb7900b6331", default-features = false, features = ["chrono", "rustls", "tds73"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync"] }
tokio-util = { version = "0.7", features = ["compat"] }

[profile.test.junit]
path = "junit.xml"
